version: "3.3"

services:

  nginx: 
    image: nginx:latest
    ports: 
      - '1408:80'
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
    links: 
      - php

  php:
    build:
      context: ./www
      dockerfile: ./Dockerfile
    links:
      - mysql

  mysql:
    build: 
      context: ./mysql
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ruslan_test
      MYSQL_USER: rus
      MYSQL_PASSWORD: qwe123
    ports:
      - "1406:3306"
    tty: true